development:
  channel_url_generator: http://jsonip.com
  channel_url_function: ip
  wap_url_barcode: http://qr.liantu.com/api.php?text=
  21tb_api: http://v4.21tb.com/open
  21tb_appkey: 6F399068B9B74CBE9FF374AEBCEE8DB2
  21tb_secrect: 92A13756F1EB47339F199C081B731DC7
  21tb_corpcode: htbroker
  21tb_uri_loadAllUser: /v1/uc/user/loadAllUsers
  21tb_uri_syncOrganizes: /v1/uc/organize/syncOrganizes
  21tb_uri_removeOrganizes: /v1/uc/organize/removeAllOrganizesWithoutMembers
  21tb_uri_syncPositions: /v1/uc/position/syncPositions
  21tb_uri_syncUsers: /v1/uc/user/syncUsers
  21tb_uri_getReportList: /v1/report/report/getOnlineCourseReportList
  21tb_uri_getExamReportList: /v1/report/report/getExamReportList
  21tb_uri_getExamInvigilates: /v1/ems/exam/getExamInvigilates

test:
  channel_url_generator: http://188.188.114.15:8082/CRH-KH8201.action?
  channel_url_function: short_url
  wap_url_barcode: http://qr.liantu.com/api.php?text=
  21tb_api: http://v4.21tb.com/open
  21tb_appkey: 6F399068B9B74CBE9FF374AEBCEE8DB2
  21tb_secrect: 92A13756F1EB47339F199C081B731DC7
  21tb_corpcode: htbroker
  21tb_uri_loadAllUser: /v1/uc/user/loadAllUsers
  21tb_uri_syncOrganizes: /v1/uc/organize/syncOrganizes
  21tb_uri_removeOrganizes: /v1/uc/organize/removeAllOrganizesWithoutMembers
  21tb_uri_syncPositions: /v1/uc/position/syncPositions
  21tb_uri_syncUsers: /v1/uc/user/syncUsers
  21tb_uri_getReportList: /v1/report/report/getOnlineCourseReportList
  21tb_uri_getExamReportList: /v1/report/report/getExamReportList
  21tb_uri_getExamInvigilates: /v1/ems/exam/getExamInvigilates

production:
  channel_url_generator: http://188.188.114.15:8082/CRH-KH8201.action?
  channel_url_function: short_url
  wap_url_barcode: http://qr.liantu.com/api.php?text=
  21tb_api: http://v4.21tb.com/open
  21tb_appkey: 6F399068B9B74CBE9FF374AEBCEE8DB2
  21tb_secrect: 92A13756F1EB47339F199C081B731DC7
  21tb_corpcode: htbroker
  21tb_uri_loadAllUser: /v1/uc/user/loadAllUsers
  21tb_uri_syncOrganizes: /v1/uc/organize/syncOrganizes
  21tb_uri_removeOrganizes: /v1/uc/organize/removeAllOrganizesWithoutMembers
  21tb_uri_syncPositions: /v1/uc/position/syncPositions
  21tb_uri_syncUsers: /v1/uc/user/syncUsers
  21tb_uri_getReportList: /v1/report/report/getOnlineCourseReportList
  21tb_uri_getExamReportList: /v1/report/report/getExamReportList
  21tb_uri_getExamInvigilates: /v1/ems/exam/getExamInvigilates
